# Start Page
<Start_page>
    name: "Start_page"
    # MDFloatLayout:  
    MDBoxLayout:
        orientation: 'vertical'
        md_bg_color: "orange"
        Image:
            source: "assets/images/p5.png"
        
        # Video:
        #     source: "../assets/videos/v1.mp4"
        #     state: 'play'
        #     # options: {'fit-mode':'contain'}
        #     eos: 'loop'
        #     allow_stretch: True